# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

dist : focal

os:
  - linux

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
       arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env: TOOLSET=gcc TEST_SUITE=arithmetic_tests
      addons:
        apt:
          packages:
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - libmpfi-dev
            - libtommath-dev

    - os: linux
       arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env: TOOLSET=gcc TEST_SUITE=cpp_int_tests
      addons:
        apt:
          packages:
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - libmpfi-dev
            - libtommath-dev

    - os: linux
       arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env: TOOLSET=gcc TEST_SUITE=functions_and_limits
      addons:
        apt:
          packages:
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - libmpfi-dev
            - libtommath-dev

    - os: linux
       arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env: TOOLSET=gcc TEST_SUITE="conversions performance"
      addons:
        apt:
          packages:
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - libmpfi-dev
            - libtommath-dev

    - os: linux
       arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env: TOOLSET=gcc TEST_SUITE=misc
      addons:
        apt:
          packages:
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - libmpfi-dev
            - libtommath-dev

    - os: linux
       arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env: TOOLSET=gcc TEST_SUITE="compile_fail examples"
      addons:
        apt:
          packages:
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - libmpfi-dev
            - libtommath-dev

    - os: linux
       arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env: TOOLSET=gcc TEST_SUITE=concepts
      addons:
        apt:
          packages:
            - libgmp-dev
            - libmpfr-dev
            - libmpc-dev
            - libmpfi-dev
            - libtommath-dev


install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init libs/polygon
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/multiprecision
  - python tools/boostdep/depinst/depinst.py multiprecision
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - (cd libs/config/test && ../../../b2 config_info_travis_install toolset=$TOOLSET && ./config_info_travis)
  - (cd libs/multiprecision/test && ../../../b2 -j3 toolset=gcc $TEST_SUITE define=CI_SUPPRESS_KNOWN_ISSUES define=SLOW_COMPILER)

notifications:
  email:
    on_success: always

